- hosts: all
  become: true

  tasks:
    - name: run container
      docker_container:
        name: app
        state: started
        restart: true
        image: "tequillasunset/pipeline-template:latest"
        pull: always
        ports:
          - "80:3000"