name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USER}}/pipeline-template:latest

  update-images:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: ondeeuto
      run: ls
    - name: update
      run: ansible-playbook -i infra/terraform/inventory infra/ansible/pull_and_run.yaml
                                                    
