name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USER}}/pipeline-template:latest

  update-images:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: configurar credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{vars.aws_region}}
    - name: Download ansible inventory
      run: aws s3 cp s3://${{ vars.bucket_name }}/inventory .
    - name: primary SSH key
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/id_rsa
        ssh-add /home/runner/.ssh/id_rsa
    - name: update
      run: ansible-playbook -i inventory infra/ansible/pull_and_run.yaml